### ISSUE TITLE
analyzer.summary() report that total_time < overall_io_time when the timestamp across multiple nodes are not synchronized. 

### ISSUE THREAD

**Issue by Jye-525** [hariharan-devarajan/dftracer#158]
Run the DLIO_benchmark with unet3d across 2 nodes. The timestamps across these two nodes are not synchronized (the difference between these two nodes > 60s).  

The output of the analyzer.summary() report that total_time < overall_io_time:
<img width="1325" alt="image" src="https://github.com/user-attachments/assets/4740bf1a-cc0b-43cb-8cfd-9309bac57ec4">

**Comment by hariharan-devarajan** [comment]
Closing as this was fixed.
